### ISSUE TITLE
Silent uninstaller not so silent.

### ISSUE THREAD

**Issue by Jookadin** [mbos/Pass4Win#41]
When running uninstall.exe /S, a messagebox appears asking if i permanently want to remove pass4win.

**Comment by mbos** [comment]
Hi,

I'm not sure which version you used :-)

As of 1.06 NSIS is used to generate the installer, I did not include silent install or uninstall features. Did you find that switch in documentation or ???

**Comment by Jookadin** [comment]
Hello Mike.

I'm currently trying to make a "chocolatey" (chocolatey.org) package, to autoinstall/uninstall.

in the registry DB, it has a "QuietUninstallString" containing: "C:\Program Files (x86)\Pass4Win\uninstall.exe" /S

I don't recall seeing that string in version 1.05.

EDIT: I used version 1.06.

**Comment by mbos** [comment]
I had troubles with installers. Version 1.0.6 is the first using NSIS.
There is no silent install or install by design, maybe by chance :)

I'll try to include silent modes in the 1.0.7 and up.

Thanks for making it available through chocolatey!
Op 7 sep. 2015 13:26 schreef "Morten Olsen" notifications@github.com:

**Comment by mbos** [comment]
Right it now installs silent by default and uninstalls honoring the /S flag c448d8e6e67b818544ed4cfe40f173a503138262

From 1.0.7 on and further :-)

**Comment by Jookadin** [comment]
Awesome, when are you releasing 1.0.7?

I'd like to publish that one on chocolatey, so im sure that the autoinstall / autouninstall works :)

**Comment by mbos** [comment]
Somewhere end of this week I think
