### ISSUE TITLE
Not working on win 10

### ISSUE THREAD

**Issue by JacobStokholm** [mbos/Pass4Win#68]
## Event viewer Error log

Faulting application name: Pass4Win.exe, version: 1.1.2.0, time stamp: 0x5618164d
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f3b2a
Exception code: 0xe0434352
Fault offset: 0x000b3e28
Faulting process id: 0x5814
Faulting application start time: 0x01d104ebc1bb9bf7
Faulting application path: C:\Program Files (x86)\Pass4Win\Pass4Win.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 30b9dc30-7b9a-4989-888a-05fa283c0feb
Faulting package full name: 
Faulting package-relative application ID:

---

Application: Pass4Win.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
Stack:
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pass4Win.frmMain, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
   at Pass4Win.frmMain..ctor()
   at Pass4Win.Program.Main()

Fault bucket 128931706737, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Pass4Win.exe
P2: 1.1.2.0
P3: 5618164d
P4: Anonymously Hosted DynamicMethods Assembly
P5: 0.0.0.0
P6: 0
P7: 0
P8: ffffffff
P9: QCQUMZNLVZFTVMBQQ2DV1TYSC5H01EH3
P10: 

Attached files:
C:\Users\Jacob\AppData\Local\Temp\WER166B.tmp.WERInternalMetadata.xml
C:\Users\Jacob\AppData\Local\Temp\WER19F6.tmp.appcompat.txt
C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A16.tmp.dmp
C:\Users\Jacob\AppData\Local\Temp\WER1BBD.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Pass4Win.exe_5b70de2d94b16f522215fb71b1381234ff8a14b_b960b5a8_4cae1bba

Analysis symbol: 
Rechecking for solution: 0
Report Id: 30b9dc30-7b9a-4989-888a-05fa283c0feb
Report Status: 4104
Hashed bucket: e13b440584b9c23ec4d4a11b9a57fbca
NsGroup=windows8
ApplicationIdentity=0C5829CCD7C617EB6C898A86E0658287

**Comment by mbos** [comment]
It works fine on Windows 10, I use it myself with Windows 10. 

This error indicates that it misses a reference, most likely a dll as .net is standard supplied with windows 10. Did you install it the program or build it, because the directory C:\Users\Jacob\Desktop\Release\ is somewhat weird for either :-)

**Comment by TechnicallyJoe** [comment]
Hi Mbos. I was the one who directed Jacob to send this issue.

I wanted let jacob see the program and give me some feedback as to what he thought.
To this end, we installed it on his computer, using your latest release
https://github.com/mbos/Pass4Win/releases - version 1.1.2

It installed fine, and opening it the first time, went smoothly, we inserted the values (Git account, password location, gpg.exe location etc) and then it crashed. No error, no nothing.

If you try to reopen it, on his computer, it crashes instantly with the above error. (The error was found in the event viewer -> Application)

We then tried a build that i had made, which is why the path is weird. - (which didn't work either)
He has edited the above comment, to show the correct one... "C:\Program Files (x86)\Pass4Win\Pass4Win.exe"

**Comment by mbos** [comment]
Okay,
Like I said it's missing an assembly, the CLR20r3 is an error for that. The missing assembly is:
Anonymously Hosted DynamicMethods Assembly which could be anything. So the program is missing a dll, either from Pass4Win or from .net.
It might be a virusscanner, it may be a corrupt .net installation, it could be anything

I'm sorry if this doesn't help, but that's all I can gleam from the error. I did not see this one in bugsnap so maybe that dll is missing or blocked by virusscan?

**Comment by TechnicallyJoe** [comment]
He was missing Git. It's all fixed now!
